apiVersion: v1
kind: Pod
metadata:
  name: fluentd-elasticsearch
  namespace: kube-system
spec:
  containers:
  - name: fluentd-elasticsearch
    image: gcr.io/eldarion-gondor/logging-agent:latest
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 100m
    env:
    volumeMounts:
    - name: varlog
      mountPath: /varlog
    - name: containers
      mountPath: /var/lib/docker/containers
  volumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: containers
    hostPath:
      path: /var/lib/docker/containers
